name: Run the exchangerizer script
on: [workflow_dispatch]

jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: requirements
              run: pip3 install -r requirements.txt
            - name: run script
              run: python3 exchangerizer.py
            - name: view output
              run: cat rates.txt
            
            